# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Symantec-PCAnywhere-Profile
version:      0.05
version_from: lib/Symantec/PCAnywhere/Profile.pm
installdirs:  site
requires:
    Carp:                          0
    Compress::Zlib:                0
    Digest::MD5:                   0
    MIME::Base64:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
